#pragma config(Motor,  port1,           MVolt,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           tw,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           th,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           fo,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           fi,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           si,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           se,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ei,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ni,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          te,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(0==0)
{
	motor[MVolt] = 127;
	motor[tw] = 127;
	motor[th] = 127;
}


}
