#pragma config(Sensor, dgtl1,  JLeft,          sensorTouch)
#pragma config(Sensor, dgtl2,  JRight,         sensorTouch)
#pragma config(Sensor, dgtl3,  JUp,            sensorTouch)
#pragma config(Sensor, dgtl4,  JDown,          sensorTouch)
#pragma config(Sensor, dgtl5,  Shift,          sensorTouch)
#pragma config(Sensor, dgtl6,  Open,           sensorTouch)
#pragma config(Sensor, dgtl7,  Close,          sensorTouch)
#pragma config(Motor,  port9,           Base,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int BS=0;
	int JUD=0;
	int SH=0;
	int CL=0;
while(true)
{
	//--------------------Control the AX1 of the robot----------------------
	if( SensorValue[JUp] == 1 )//if joystick is tilted left
	{
		if( SensorValue[Shift] == 1 )
		{
			motor[Arm1] = SH;//turn base motor left
			if(SH<127)
			{
				SH++;
			}
			wait1Msec(5);
		}
		else
		{
			motor[Arm2] = JUD;//turn base motor left
			if(JUD<127)
			{
				JUD++;
			}
			wait1Msec(5);
		}
	}
	else if( SensorValue[JDown] == 1 )//if joystick is tilted right
	{
		if( SensorValue[Shift] == 1)
		{
			motor[Arm1] = SH;//turn base motor right
			if(SH>-127)
			{
				SH--;
	  	}
	  	wait1Msec(5);
		}
		else
		{
			motor[Arm2] = JUD;//turn base motor right
			if(JUD>-127)
			{
				JUD--;
	  	}
	  	wait1Msec(5);
		}
	}
	else if( SensorValue[JUp]+SensorValue[JDown]+SensorValue[Open]+SensorValue[Close]+SensorValue[JLeft]+SensorValue[JRight]==0 )
	{
		motor[Arm2] = JUD;
		motor[Arm1] = SH;
		motor[Claw] = CL;
		motor[port9] = BS;
		wait1Msec(5);
	}
	else if( SensorValue[Open] == 1)
	{
		motor[Claw] = CL;
		if(CL<127)
		{
			CL++;
		}
		wait1Msec(5);
	}
	else if( SensorValue[Close] == 1)
	{
		motor[Claw] = CL;
		if(CL>-127)
		{
			CL--;
		}
		wait1Msec(5);
	}
	else if( SensorValue[JRight] == 1)
	{
		motor[port9] = BS;
		if(BS<127)
		{
			BS++;
		}
		wait1Msec(5);
	}
	else if( SensorValue[JLeft] == 1)
	{
		motor[port9] = BS;
		if(BS>-127)
		{
			BS--;
		}
		wait1Msec(5);
	}









}
}
