#pragma config(Sensor, dgtl1,  up,             sensorTouch)
#pragma config(Sensor, dgtl2,  down,           sensorTouch)
#pragma config(Sensor, dgtl3,  left,           sensorTouch)
#pragma config(Sensor, dgtl4,  right,          sensorTouch)
#pragma config(Sensor, dgtl5,  shift,          sensorTouch)
#pragma config(Sensor, dgtl6,  open,           sensorTouch)
#pragma config(Sensor, dgtl7,  close,          sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorTouch)
#pragma config(Sensor, dgtl9,  ,               sensorTouch)
#pragma config(Sensor, dgtl10, ,               sensorTouch)
#pragma config(Sensor, dgtl11, ,               sensorTouch)
#pragma config(Sensor, dgtl12, ,               sensorTouch)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ax2,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ax1,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           base,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	while(true)
	{
		/*
		if(SensorValue[up] == 1)
		{
			if(SensorValue[shift] == 1)
			{
				motor[ax1] = 50;
				motor[ax2] = 0;
			}
			else
			{
				motor[ax2] = 50;
				motor[ax1] = 0;
			}
		}
		else if(SensorValue[down] == 1)
		{
			if(SensorValue[shift] == 1)
			{
				motor[ax1] = -50;
				motor[ax2] = 0;
			}
			else
			{
				motor[ax2] = -50;
				motor[ax1] = 0;
			}
		}
		else if(SensorValue[right] == 1)
		{
			motor[base] = 50;
		}
		else if(SensorValue[left] == 1)
		{
			motor[base] = -50;
		}
		*/
		while(SensorValue[right] == 1)
		{
		  for(int i=0;i<=127;i++)
		  {
				motor[base] = i;
			}
		}

		while(SensorValue[left] == 1)
		{
		  for(int i=0;i>=-127;i--)
		  {
				motor[base] = i;
			}
		}

		while(SensorValue[up] == 1)
		{
		  for(int i=0;i<=127;i++)
		  {
				motor[ax2] = i;
			}
		}

		while(SensorValue[down] == 1)
		{
		  for(int i=0;i>=-127;i--)
		  {
				motor[ax2] = i;
			}
		}
	}

}
