#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in3,    Light,          sensorReflection)
#pragma config(Motor,  port2,           Feed,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           Sweep,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          Flash,         tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
  turnFlashlightOn(port10, -127);
  if(SensorValue(Light) > 100)
  {
  motor[Feed] = 127;
  }
}

}
