#pragma config(Sensor, in3,    Light,          sensorReflection)
#pragma config(Motor,  port2,           Feed,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           Sweep,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          Flash,         tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x = 1;
	turnFlashlightOn(port10, -127);
	while(x>=1)//This block feeds 1 marble into the system for detection
	{
		motor[port2] = -127;
		wait1Msec(100);
		motor[port2] = 127;
		wait1Msec(100);
		motor[port2] = 0;
		wait1Msec(250);
		if (SensorValue(Light) < 20)//detect if the marble is clear
		{
			motor[Sweep] = 127;
			wait1Msec(150);
			motor[Sweep] = -127;
			wait1Msec(150);
			motor[Sweep] = 0;
			wait1Msec(100);
		}
		else if (SensorValue(Light) > 80)//detect if the ball is colored
		{
			motor[Sweep] = -127;
			wait1Msec(150);
			motor[Sweep] = 127;
			wait1Msec(150);
			motor[Sweep] = 0;
			wait1Msec(100);
		}
		else
		{
			motor[Sweep] = 0;
			wait1Msec(100);
		}
	}

	//Clear Value is 20
	//50+ for no ball
	//Color Value is 100?

}
