#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(0==0)
{
motor[left] = 127;
}



}
