#pragma config(Motor,  port2,           DriveLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           DriveRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           BigSucc,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           NippleMeister, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ScissorLift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ConeIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BaseForklift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ConeIntakeScissor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[port3] = 127;
	motor[port2] = 127;
	motor[port6] = 127;
	wait1Msec(1200);
	motor[port6] = 0;
	wait1Msec(750);
	motor[port6] = -127;
	motor[port3] = 0;
	motor[port2] = 0;
	wait1Msec(1200);
	motor[port3] = 127;
	motor[port2] = -127;
	wait1Msec(2200);
	motor[port6] = 0;
	motor[port3] = 127;
	motor[port2] = 127;
	wait1Msec(3500);
	motor[port3] = 0;
	motor[port2] = 0;
	motor[port6] = 127;
	wait1Msec(1200);
	motor[port6] = 0;
	motor[port3] = -127;
	motor[port2] = -127;
	wait1Msec(500);
	motor[port3] = 0;
	motor[port2] = 0;
	motor[port6] = -127;
	wait1Msec(1200);
	motor[port6] = 0;
	motor[port3] = -127;
	motor[port2] = -75;
	wait1Msec(1000);
	motor[port2] = -127;
	motor[port3] = 127;
	wait1Msec(2400);
	motor[port3] = 127;
	motor[port2] = 127;
	wait1Msec(1000);
	motor[port3] = 0;
	motor[port2] = 0;
	motor[port6] = 127;
	wait1Msec(1200);
	motor[port6] = 0;
	motor[port3] = 127;
	motor[port2] = 127;
	wait1Msec(1000);
	motor[port6] = -127;
	motor[port3] = 127;
	motor[port2] = -127;
	wait1Msec(1200);
	motor[port6] = 0;
	wait1Msec(1000);
	motor[port2] = 0;
	motor[port3] = 0;






}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		while(1==1)
		{
			//Tank Control Drive Motors
			motor[DriveLeft] = vexRT[Ch3];//Set Left motor to Y axis on Left Joystick
			motor[DriveRight] = vexRT[Ch2];//Set Right motor to Y axis on Right Joystick

			//Hand Control
			if(vexRT[Btn8U] == 1)//If button 8 is pressed Move Hand Motor
			{
					motor[port8] = 127;
			}
				else if (vexRT[Btn8U] == 0)
			{
					motor[port8] = 0;
			}

				if(vexRT[Btn8R] == 1)
			{
					motor[port8] = -127;
			}
				else if (vexRT[Btn8R] == 0)
			{
					motor[port8] = 0;
			}
						if(vexRT[Btn8L] == 1)//If button 8 is pressed Move Hand Motor
			{
					motor[port4] = 127;
			}
				else if (vexRT[Btn8L] == 0)
			{
					motor[port4] = 0;
			}

				if(vexRT[Btn8D] == 1)
			{
					motor[port4] = -127;
			}
				else if (vexRT[Btn8D] == 0)
			{
					motor[port4] = 0;
			}
				if(vexRT[Btn6U] == 1)
			{
					motor[port6] = 127;
			}
				else if(vexRT[Btn6D] == 1)
			{
					motor[port6] = -127;
			}
				else
			{
					motor[port6] = 0;
			}
				if(vexRT[Btn5U] == 1)
			{
					motor[port5] = 127;
			}
				else if(vexRT[Btn5D] == 1)
			{
					motor[port5] = -127;
			}
				else
			{
					motor[port5] = 0;
			}
		}
	}
}
