#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Right1,        tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           ArmBackup1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ArmBackup2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ConeScoop,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		//Tank Control Drive Motors
		motor[Left1] = vexRT[Ch3];//Set Left motor to Y axis on Left Joystick
		motor[Right1] = vexRT[Ch2];//Set Right motor to Y axis on Right Joystick

		//Hand Control
		if(vexRT[Btn8U] == 1)//If button 8 is pressed Move Hand Motor
		{
			motor[port8] = 127;
		}
		else if (vexRT[Btn8U] == 0)
		{
			motor[port8] = 0;
		}

		if(vexRT[Btn8R] == 1)
		{
			motor[port8] = -127;
		}
		else if (vexRT[Btn8R] == 0)
		{
			motor[port8] = 0;
		}

		if(vexRT[Btn8U] == 1)
		{
			motor[port7] = 127;
		}
		else if (vexRT[Btn8U] == 0)
		{
			motor[port7] = 0;

			if(vexRT[Btn8L] == 1)
			{
				motor[port4] = -50;
			}
			else if (vexRT[Btn8L] == 0)
			{
				motor[port4] = 0;
			}
			if(vexRT[Btn8D] == 1)
			{
				motor[port4] = 50;
			}
			else if (vexRT[Btn8D] == 0)


			motor[port4] = 0;
		}
		if(vexRT[Btn6U] == 1)
		{
			motor[port6] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[port6] = -127;
		}
		else
		{

			motor[port6] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[port5] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[port5] = -127;
		}
		else
		{
			motor[port5] = 0;
		}
		if(vexRT[Btn6U] == 1)
		{
			motor[port6] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[port6] = -127;
		}
		else
		{
			motor[port6] = 0;
		}

		motor[port9] = 0;

		if(vexRT[Btn7L] == 1)
		{
			motor[port9] = 127;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[port9] = -127;
		}
		else
		{
			motor[port9] = 0;
		}
	}
}
